# 服务配置
Server:
  RunMode: debug # 设置gin 的运行模式
  HttpPort: 8080 # 默认的 HTTP 监听端口
  ReadTimeout: 60 # 允许读取和写入的最大持续时间
  WriteTimeout: 60
#应用配置
App:
  DefaultPageSize: 6 # 默认每页数量
  MaxPageSize: 100 # 所允许的最大每页数量
  LogSavePath: storage/logs # 默认的应用日志存储路径
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  #  上传图片配置
  UploadImageSavePath: storage/uploads/image # 上传文件的最终保存目录
  UploadImageServerUrl: /static/image # 上传文件后用于展示的文件服务地址
  UploadImageMaxSize: 5 # MB 最大空间大小
  UploadImageAllowExts: # 文件名后缀
    - .jpg
    - .jpeg
    - .png
  # 上传 markdown 文件配置
  UploadMDSavePath: storage/uploads/md
  UploadMDServerUrl: /static/md
  UploadMDAllowExts:
    - .md
  UploadMDMaxSize: 10 # MB 最大空间大小
  DefaultContextTimeout: 20 # 请求超时处理
#数据库配置
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: blog_service
  Table_prefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
# 鉴权配置
JWT:
  Secret: hzj # 不能外泄
  Issuer: blog-service
  Expire: 7200
# 邮件配置
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: 2398960068@qq.com
  Password: fmumyautezwbebbj # 授权码
  IsSSL: true
  From: 2398960068@qq.com
  To:
    - 2398960068@qq.com
# jaeger tracer 配置
Tracer:
  ServiceName: go-blog
  HostPort: 127.0.0.1:6831